
export const Home = () => {
    return(
        <div>
            <h1>Home</h1>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit quos veritatis tempore amet aliquid dolorum deleniti porro sit ducimus quod neque cum enim, deserunt natus nisi repudiandae. Eveniet, aspernatur corrupti. Obcaecati dolore explicabo eum incidunt vel laudantium alias ut atque? Recusandae odit corporis asperiores modi veniam ullam harum quasi repudiandae corrupti cupiditate? Error fuga provident nihil esse voluptatibus ullam, sit impedit aut dolorum a inventore dolor tempore ea maxime reprehenderit deleniti unde eos rerum vero voluptates cupiditate animi molestias. Voluptatum perspiciatis distinctio deserunt non dolorem nobis officia atque voluptatem! Perferendis rerum dicta exercitationem odio autem cum maiores eligendi consequatur voluptates?</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit quos veritatis tempore amet aliquid dolorum deleniti porro sit ducimus quod neque cum enim, deserunt natus nisi repudiandae. Eveniet, aspernatur corrupti. Obcaecati dolore explicabo eum incidunt vel laudantium alias ut atque? Recusandae odit corporis asperiores modi veniam ullam harum quasi repudiandae corrupti cupiditate? Error fuga provident nihil esse voluptatibus ullam, sit impedit aut dolorum a inventore dolor tempore ea maxime reprehenderit deleniti unde eos rerum vero voluptates cupiditate animi molestias. Voluptatum perspiciatis distinctio deserunt non dolorem nobis officia atque voluptatem! Perferendis rerum dicta exercitationem odio autem cum maiores eligendi consequatur voluptates?</p>
           
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit quos veritatis tempore amet aliquid dolorum deleniti porro sit ducimus quod neque cum enim, deserunt natus nisi repudiandae. Eveniet, aspernatur corrupti. Obcaecati dolore explicabo eum incidunt vel laudantium alias ut atque? Recusandae odit corporis asperiores modi veniam ullam harum quasi repudiandae corrupti cupiditate? Error fuga provident nihil esse voluptatibus ullam, sit impedit aut dolorum a inventore dolor tempore ea maxime reprehenderit deleniti unde eos rerum vero voluptates cupiditate animi molestias. Voluptatum perspiciatis distinctio deserunt non dolorem nobis officia atque voluptatem! Perferendis rerum dicta exercitationem odio autem cum maiores eligendi consequatur voluptates?</p>

            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit quos veritatis tempore amet aliquid dolorum deleniti porro sit ducimus quod neque cum enim, deserunt natus nisi repudiandae. Eveniet, aspernatur corrupti. Obcaecati dolore explicabo eum incidunt vel laudantium alias ut atque? Recusandae odit corporis asperiores modi veniam ullam harum quasi repudiandae corrupti cupiditate? Error fuga provident nihil esse voluptatibus ullam, sit impedit aut dolorum a inventore dolor tempore ea maxime reprehenderit deleniti unde eos rerum vero voluptates cupiditate animi molestias. Voluptatum perspiciatis distinctio deserunt non dolorem nobis officia atque voluptatem! Perferendis rerum dicta exercitationem odio autem cum maiores eligendi consequatur voluptates?</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit quos veritatis tempore amet aliquid dolorum deleniti porro sit ducimus quod neque cum enim, deserunt natus nisi repudiandae. Eveniet, aspernatur corrupti. Obcaecati dolore explicabo eum incidunt vel laudantium alias ut atque? Recusandae odit corporis asperiores modi veniam ullam harum quasi repudiandae corrupti cupiditate? Error fuga provident nihil esse voluptatibus ullam, sit impedit aut dolorum a inventore dolor tempore ea maxime reprehenderit deleniti unde eos rerum vero voluptates cupiditate animi molestias. Voluptatum perspiciatis distinctio deserunt non dolorem nobis officia atque voluptatem! Perferendis rerum dicta exercitationem odio autem cum maiores eligendi consequatur voluptates?</p>
           
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit quos veritatis tempore amet aliquid dolorum deleniti porro sit ducimus quod neque cum enim, deserunt natus nisi repudiandae. Eveniet, aspernatur corrupti. Obcaecati dolore explicabo eum incidunt vel laudantium alias ut atque? Recusandae odit corporis asperiores modi veniam ullam harum quasi repudiandae corrupti cupiditate? Error fuga provident nihil esse voluptatibus ullam, sit impedit aut dolorum a inventore dolor tempore ea maxime reprehenderit deleniti unde eos rerum vero voluptates cupiditate animi molestias. Voluptatum perspiciatis distinctio deserunt non dolorem nobis officia atque voluptatem! Perferendis rerum dicta exercitationem odio autem cum maiores eligendi consequatur voluptates?</p>

            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit quos veritatis tempore amet aliquid dolorum deleniti porro sit ducimus quod neque cum enim, deserunt natus nisi repudiandae. Eveniet, aspernatur corrupti. Obcaecati dolore explicabo eum incidunt vel laudantium alias ut atque? Recusandae odit corporis asperiores modi veniam ullam harum quasi repudiandae corrupti cupiditate? Error fuga provident nihil esse voluptatibus ullam, sit impedit aut dolorum a inventore dolor tempore ea maxime reprehenderit deleniti unde eos rerum vero voluptates cupiditate animi molestias. Voluptatum perspiciatis distinctio deserunt non dolorem nobis officia atque voluptatem! Perferendis rerum dicta exercitationem odio autem cum maiores eligendi consequatur voluptates?</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit quos veritatis tempore amet aliquid dolorum deleniti porro sit ducimus quod neque cum enim, deserunt natus nisi repudiandae. Eveniet, aspernatur corrupti. Obcaecati dolore explicabo eum incidunt vel laudantium alias ut atque? Recusandae odit corporis asperiores modi veniam ullam harum quasi repudiandae corrupti cupiditate? Error fuga provident nihil esse voluptatibus ullam, sit impedit aut dolorum a inventore dolor tempore ea maxime reprehenderit deleniti unde eos rerum vero voluptates cupiditate animi molestias. Voluptatum perspiciatis distinctio deserunt non dolorem nobis officia atque voluptatem! Perferendis rerum dicta exercitationem odio autem cum maiores eligendi consequatur voluptates?</p>
           
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit quos veritatis tempore amet aliquid dolorum deleniti porro sit ducimus quod neque cum enim, deserunt natus nisi repudiandae. Eveniet, aspernatur corrupti. Obcaecati dolore explicabo eum incidunt vel laudantium alias ut atque? Recusandae odit corporis asperiores modi veniam ullam harum quasi repudiandae corrupti cupiditate? Error fuga provident nihil esse voluptatibus ullam, sit impedit aut dolorum a inventore dolor tempore ea maxime reprehenderit deleniti unde eos rerum vero voluptates cupiditate animi molestias. Voluptatum perspiciatis distinctio deserunt non dolorem nobis officia atque voluptatem! Perferendis rerum dicta exercitationem odio autem cum maiores eligendi consequatur voluptates?</p>
        </div>
    )
}